### PR TITLE
Timeout compatible with ruby1.8.7

### PR DESCRIPTION
**Pull request by alvarezmelissa87**

### CODE REVIEW

**Comment by adelevie** [comment]
Looks fine to me. What say you, @gaffneyc?

**Comment by schleg** [comment]
@alvarezmelissa87 @adelevie i'm helping out with maintenance on this gem. I see it's been almost a year so may not care anymore, but can you educate me how a version check for < 1.9 tells us whether it's REE vs. JRuby? Thanks

**Comment by adelevie** [comment]
> typhoeus uses milisecs with ree and secs with jruby 

^ seems to explain it.

**Comment by bensheldon** [comment]
I think these changes are stale by now 😞  Please ping me if you would like to re-open and move this forward.

**Pull request closed without merging**
